version: '3'
  services:
    traefik:
      image: traefik:latest
      container_name: traefik
      hostname: traefik
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      ports:   
        - 80:80  
        - 443:443
        - 2222:2222    
      networks:
        - traefik-network
        - gitea-network
      volumes:
        - /certs:/certs:ro
        - traefik_app:/etc/traefik/
        - traefik_data:/etc/letsencrypt/
        - traefik_log:/var/log/traefik/
        - /etc/localtime:/etc/localtime:ro
      env_file: .env
      environment:
        - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}                          
        - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
        - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
        - CLOUDFLARE_ZONE_API_TOKEN=${CLOUDFLARE_ZONE_API_TOKEN}
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gitea-network"

    gitea:
      image: gitea/gitea:1
      container_name: gitea
      hostname: gitea
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      depends_on:
        - traefik
      networks:
        - gitea-network
      volumes:
        - gitea_data:/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      environment:
        - USER_UID=112
        - USER_GID=119
        - RUN_MODE=prod
        - HTTP_PORT=3000
        - SSH_LISTEN_PORT=4000
        - ROOT_URL='https://git.technerdonline.com'
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://gitea:3000 || exit 1"]
        interval: 1m30s
        timeout: 10s
        retries: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gitea-network"
        
    plantuml-server:
      image: jgraph/plantuml-server:latest
      container_name: plantuml-server
      restart: unless-stopped
      security_opt: 
        - no-new-privileges:true
      networks:
        - gitea-network
      volumes:
        - /app/drawio/fonts:/usr/share/fonts/drawio
      labels:
        - "traefik.enable=false"
        
    image-export:
      image: jgraph/export-server:latest
      container_name: export-server
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - gitea-network
      volumes:
        - /app/drawio/fonts:/usr/share/fonts/drawio
      labels:
        - "traefik.enable=false"

    drawio:
      image: jgraph/drawio:latest
      container_name: drawio
      hostname: drawio
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      depends_on:
        - traefik
        - plantuml-server
        - image-export
      networks:
        - gitea-network
      volumes:
        - /app/drawio/PostConfig.js:/usr/local/tomcat/webapps/draw/js/PostConfig.js
        - /app/drawio/PreConfig.js:/usr/local/tomcat/webapps/draw/js/PreConfig.js
      environment:
        - PLANTUML_URL=http://plantuml-server:8080/
        - EXPORT_URL=http://image-export:8000/
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://drawio:8080 || exit 1"]
        interval: 1m30s
        timeout: 10s
        retries: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=gitea-network"         
volumes:
  traefik_app:
    external: true
  traefik_data: 
    external: true
  traefik_log: 
    external: true
  gitea_data:
    external: true
    
networks:
   traefik-network:
     external: true
   gitea-network:
     external: true
