##### STATIC CONFIG #####
global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  rootCAs:
    - /etc/traefik/ssl/cloudflare.crt
    - /etc/traefik/ssl/rootca.crt
  
api:
  dashboard: true
  insecure: false
  
ping:
  entryPoint: "traefik"
  manualRouting: false

metrics:
  prometheus:
    entryPoint: "traefik"
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: false
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

log:
  level: INFO
  filePath: /etc/traefik/log/traefik.log
  format: json

accessLog:
  filePath: /etc/traefik/log/access.log
  format: json
  fields:
    defaultMode: keep
    names:
      clientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: edwin@thelyoncompany.com
      storage: /etc/traefik/ssl/acme.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - '1.0.0.1:53'
          - '1.0.0.1:53'

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      middlewares:
        - cf-passtlsclientcert@file
        - secure-header@file
      tls:
        options: default
        certResolver: letsencrypt
        domains:
          - main: "technerdonline.com"
            sans:
              - "*.technerdonline.com"
          - main: "technerdonline.net"
            sans:
              - "*.technerdonline.net"

http:
  #SERVICES
  services:
    gitea:
      loadBalancer:
        servers:
          - url: http://gitea:3000
    
    drawio:
      loadBalancer:
        servers:
          - url: http://drawio:8080

    code-server:
      loadBalancer:
        servers:
          - url: http://code-server:8443

    nginx:
      loadBalancer:
        servers:
          - url: http://nginx:80

  #ROUTERS
  routers:
    #TRAEFIK
    api-redirect:
      rule: "Host(`traefik.technerdonline.com`)"
      entryPoints:
        - web
      service: api@internal
    #TRAEFIK-SECURE
    api-router:
      rule: "Host(`traefik.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - basic-auth
        - csp-header
      service: api@internal
    #GITEA
    gitea-redirect:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - web
      service: gitea
    #GITEA-SECURE  
    gitea-router:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - gitea-header
      service: gitea
    #DRAWIO  
    drawio-redirect:
      rule: "Host(`drawio.technerdonline.com`)"
      entryPoints:
        - web
      service: drawio
    #DRAWIO-SECURE
    drawio-router:
      rule: "Host(`drawio.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - basic-auth
        - gitea-header
      service: drawio
    #CODE-SERVER
    code-server-redirect:
      rule: "Host(`code-server.technerdonline.com`)"
      entryPoints:
        - web
      service: code-server
    #CODE-SERVER-SECURE
    code-server-router:
      rule: "Host(`code-server.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - basic-auth
        - gitea-header
      service: code-server
    #NGINX
    nginx-redirect:
      rule: "Host(`technerdonline.com`,`www.technerdonline.com`) || Host(`technerdonline.net`,`www.technerdonline.net`)"
      entryPoints:
        - web
      middlewares:
        - www-redirectregex
        - net-redirectregex
      service: nginx
    #NGINX-SECURE
    nginx-router:
      rule: "Host(`technerdonline.com`, `www.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - csp-header
      service: nginx
  
  #MIDDLEWARES
  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "$USER:$PASSWORD"
        usersFile: "/etc/traefik/.htpasswd"
        headerField: "X-WebAuth-User"
        removeHeader: true

    secure-header:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslRedirect: true
        forceSTSHeader: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "no-referrer"

    csp-header:
      headers:
        contentSecurityPolicy: "default-src 'self'; base-uri 'none'; object-src 'none'; manifest-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data: https:; connect-src 'self'; media-src 'self'; frame-ancestors 'self'; worker-src 'self' blob:" 
        featurePolicy: "accelerometer 'none'; ambient-light-sensor 'self'; autoplay 'none'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'none'; usb *; vr 'none'"

    gitea-header:
      headers:
        contentSecurityPolicy: "default-src 'self'; base-uri 'none'; object-src 'none'; manifest-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://*.technerdonline.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://*.technerdonline.com; img-src 'self' data: https: blob:; font-src 'self' data: https:; connect-src 'self'; media-src 'self'; frame-ancestors 'self'; worker-src 'self' blob:"
        featurePolicy: "accelerometer 'none'; ambient-light-sensor 'self'; autoplay 'none'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'self' https://twofactorauth.org https://haveibeenpwned.org; usb *; vr 'none'"
        
    cf-passtlsclientcert:
      passTLSClientCert:
        pem: true
    
    http-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    www-redirectregex:
      redirectRegex:
        regex: "^www.technerdonline.net"
        replacement: "www.technerdonline.com"
        permanent: true

    net-redirectregex:
      redirectRegex:
        regex: "^technerdonline.net"
        replacement: "technerdonline.com"
        permanent: true

tls:
  certificates:
  - certFile: /etc/traefik/ssl/cert.pem
    keyFile: /etc/traefik/ssl/key.pem
    stores: default
 
  - certFile: /etc/traefik/ssl/technerdonline.net.pem
    keyFile: /etc/traefik/ssl/technerdonline.net-key.pem
    stores: technerdonline.net

  options:
    default:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
      preferServerCipherSuites: true
      clientAuth:
        caFiles:
          - /etc/traefik/ssl/cloudflare.crt
        clientAuthType: RequireAndVerifyClientCert

    mintls13:
      minVersion: VersionTLS13
      maxVersion: VersionTLS13
      sniStrict: true
      clientAuth:
        caFiles: 
          - /etc/traefik/ssl/cloudflare.crt
        clientAuthType: RequireAndVerifyClientCert

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/ssl/cert.pem
        keyFile: /etc/traefik/ssl/key.pem

    technerdonline.net:
      defaultCertificate:
        certFile: /etc/traefik/ssl/technerdonline.net.pem
        keyFile: /etc/traefik/ssl/technerdonline.net-key.pem 
