### GLOBAL CONFIGURATION ###
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep
 
### PROVIDERS CONFIGURATION ###
providers:
  file:
    directory: /etc/traefik/
    watch: true

tls:   
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384  
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true      
    mintls13:
      minVersion: VersionTLS13
      curvePreferences:
        - CurveP521
      sniStrict: true
  
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: info@thelyoncompany.com
      storage: /etc/ssl/traefik/acme.json
      keyType: EC384
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 15
        
### STATIC CONFIGURATION ###
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: web-secure
          scheme: https
          permanent: true
    
  web-secure:
    address: :443

  ping:
    address: :8081

  metrics:
    address: :8082

ping:
  entryPoint: ping
  
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: false
    entryPoint: metrics

### DYNAMIC CONFIGURATION ###
http:

  #ROUTERS
  routers:
  
    #DASHBOARD
    api-redirect:
      rule: "Host(`technerdonline.com`,`www.technerdonline.com`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: api@internal

    #DASHBOARD SECURE
    api-router:
      rule: "Host(`technerdonline.com`,`www.technerdonline.com`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      entryPoints:
        - web-secure
      middlewares:
        - secure-headers
        - api-auth
      service: api@internal
      tls:
        certResolver: letsencrypt
        domains:
          - main: "technerdonline.com"
            sans:
              - "*.technerdonline.com"
        options: default
    
    #GITEA
    gitea-redirect:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: gitea

    #GITEA SECURE
    gitea-router:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - secure-headers
      service: gitea
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.technerdonline.com"
        options: default

    #DRAWIO
    drawio-redirect:
      rule: Host(`drawio.technerdonline.com`)
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: drawio

    #DRAWIO SECURE
    drawio-router:
      rule: Host(`drawio.technerdonline.com`)
      entryPoints:
        - web-secure
      middlewares:
        - security-headers
        - api-auth
      service: drawio
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.technerdonline.com"
        options: default

    #BITWARDEN
    bitwarden-redirect:
      rule: "Host(`vault.technerdonline.com`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: bitwarden

    #BITWARDEN SECURE
    bitwarden-router:
      rule: "Host(`vault.technerdonline.com`)"
      entryPoints:
        - web-secure
      middlewares:
        - secure-headers
      service: bitwarden
      tls:
        certResolver: letsencrypt
        domains:
          - main: "vault.technerdonline.com"
        options: default
    
    #BITWARDEN WEBSOCKET
    bitwarden-websocket-router:
      rule: "Host(`vault.technerdonline.com`) && Path(`/notifications/hub`)"
      entryPoints:
        - web-secure
      middlewares:
        - secure-headers
      service: bitwarden-websocket
      tls:
        certResolver: letsencrypt
        domains:
          - main: "*.technerdonline.com"
        options: default
        
  #MIDDLEWARES
  middlewares:
  
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
        
    www-redirect:
      redirectRegex:
        regex: "^https://(technerdonline\\.com.*)"
        replacement: "https://www.${1}"
        permanent: true

    api-auth:
      basicAuth:
        users:
          - "username:password"

    trusted-whitelist:
      ipWhiteList:
        sourceRange:
          - fd42:42:42::/64
          - 10.128.1.0/24
   
    secure-headers:
      headers:
        sslRedirect: true 
        sslForceHost: true  
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true    
        forceSTSHeader: true
        frameDeny: true
        customFrameOptionsValue: "SAMEORIGIN"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        contentSecurityPolicy: "upgrade-insecure-requests"
        featurePolicy: "accelerometer 'none'; ambient-light-sensor 'self'; autoplay 'self'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'none'; usb *; vr 'none'"
        
    gitea-headers:
      headers:
        sslRedirect: true 
        sslForceHost: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true
        customFrameOptionsValue: "SAMEORIGIN"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        contentSecurityPolicy: "upgrade-insecure-requests"  
        featurePolicy: "accelerometer 'none'; ambient-light-sensor 'self'; autoplay 'self'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'none'; usb *; vr 'none'"    


  #SERVICES
  services:
  
    gitea:
      loadBalancer:
        servers:
          - url: http://gitea:3000
    
    code-server:
      loadBalancer:
        servers:
          - url: http://code-serer:9000
    
    drawio:
      loadBalancer:
        servers:
          - url: http://drawio:8080

    bitwarden:
      loadBalancer:
        servers:
          - url: http://bitwarden:80
          
    bitwarden-websocket:
      loadBalancer:
        servers:
          - url: ws://bitwarden:3012
