##### STATIC CONFIG #####
global:
  checkNewVersion: true
  sendAnonymousUsage: false  
    
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: json
  
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  fields:
    defaultMode: keep
    names:
      clientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep
api:
  dashboard: true
  
serversTransport:
  rootCAs:
    - /etc/traefik/cloudflare.crt
    - /etc/traefik/ca.crt
      
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: acme@technerdonline.com
      storage: /etc/letsencrypt/acme.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'
#Health   
ping:
  entryPoint: "traefik"
  manualRouting: false
#Metrics
metrics:
  prometheus:
    entryPoint: "traefik"
    addEntryPointsLabels: true
    addServicesLabels: true
    manualRouting: false
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    endpoint: tcp://172.20.20.1:2376
    exposedByDefault: false
    tls:
      ca: /etc/traefik/ca.crt
      caOptional: true
      cert: /etc/traefik/server.pem
      key:  /etc/traefik/server-key.pem
  file:
    directory: /etc/traefik/
    watch: true
    
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      middlewares:
        - secure-headers
        - cf-passtlsclientcert
      tls:
        options: default
        certResolver: letsencrypt
        domains:
          - main: "technerdonline.com"
            sans:
              - "*.technerdonline.com"
  tcp:
    address: ":2222"
      
http:
  #MIDDLEWARES#
  middlewares:
    api-auth:
      basicAuth:
        users:
          - admin:password

    gitea-auth:
      basicAuth:
        users:
          - drawio:password
    
    docker-whitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32
          - 172.20.20.0/24
          - 172.20.21.0/24
          
    cloudflare-whitelist:
      ipWhiteList:
        sourceRange:
          - 173.245.48.0/20
          - 103.21.244.0/22
          - 103.22.200.0/22
          - 103.31.4.0/22
          - 141.101.64.0/18
          - 108.162.192.0/18
          - 190.93.240.0/20
          - 188.114.96.0/20
          - 197.234.240.0/22
          - 198.41.128.0/17
          - 162.158.0.0/15
          - 104.16.0.0/12
          - 172.64.0.0/13
          - 131.0.72.0/22
        ipStrategy:
          depth: 2
          
    cf-passtlsclientcert:
      passTLSClientCert:
        pem: true
        
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - HEAD
          - POST
        accessControlAllowOriginList:
          - http://*.technerdonline.com
        accessControlMaxAge: 100
        addVaryHeader: true
    
    secure-headers:
      headers:
        sslRedirect: true  
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true    
        forceSTSHeader: true
        frameDeny: true
        customFrameOptionsValue: "SAMEORIGIN"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        contentSecurityPolicy: "upgrade-insecure-requests"
        featurePolicy: "accelerometer 'none'; ambient-light-sensor 'self'; autoplay 'self'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture *; speaker 'none'; sync-xhr 'none'; usb *; vr 'none'"             
    
  #ROUTERS
  routers:
    #TRAEFIK
    api-redirect:
      rule: "Host(`traefik.technerdonline.com`)"
      entryPoint:
        - web
      service: api@internal
    #TRAEFIK-SECURE
    api-router:
      rule: "Host(`traefik.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - api-auth
      service: api@internal
    #GITEA
    gitea-redirect:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - web
      service: gitea
    #GITEA-SECURE  
    gitea-router:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - cors-headers
      service: gitea
    #DRAWIO  
    drawio-redirect:
      rule: "Host(`drawio.technerdonline.com`)"
      entryPoints:
        - web
      service: drawio
    #DRAWIO-SECURE
    drawio-router:
      rule: "Host(`drawio.technerdonline.com`)"
      entryPoints:
        - websecure
      middlewares:
        - gitea-auth
      service: drawio
      
  #SERVICES
  services:
  
    gitea:
      loadBalancer:
        servers:
          - url: http://gitea:3000
    
    drawio:
      loadBalancer:
        servers:
          - url: http://drawio:8080

tcp:
  routers:
    giteassh-router:
      rule: "Host(`git.technerdonline.com`)"
      entryPoints:
        - tcp
      service: gitea-ssh
      
  services:
    gitea-ssh:
      loadBalancer:
        servers:
          - url: tcp://gitea:4000
    
tls:
  certificates:certificates:
    - certFile: /etc/letsencrypt/domain.cert
      keyFile: /etc/letsencrypt/domain.key
      stores:
        - default
    - certFile: /etc/letsencrypt/cf-origin-cert.pem
      keyFile: /etc/letsencrypt/cf-origin-key.pem
      stores:
        - cloudflare
        
 stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/domain.cert
        keyFile: /etc/letsencrypt/domain.key
    cloudflare:
      cloudflareCertificate:
        certFile: /etc/letsencrypt/cf-origin-cert.pem
        keyFile: /etc/letsencrypt/cf-origin-key.pem
        
  options:
    default:
      minVersion: VersionTLS13
      sniStrict: true
      curvePreferences: 
        - CurveP521
        - CurveP384
      preferServerCipherSuites: true
      clientAuth:
        caFiles:
          - /etc/traefik/cloudflare.pem
        clientAuthType: RequireAndVerifyClientCert  
       
